FROM registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9

USER root

RUN microdnf install -y \
      python3 \
      python3-pip \
      java-17-openjdk-headless \
    && pip3 install --no-cache-dir ansible-rulebook \
    && microdnf clean all

ENV JAVA_HOME=/usr/lib/jvm/jre-17
ENV PATH=$JAVA_HOME/bin:$PATH

USER 1000
